spring:
  application:
    name: ${rootProject.name}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:/db/migration

management:
  endpoints:
    webm:
      exposure:
        include:
          - env
          - health
          - shutdown
    env:
      show-values: always
    health:
      show-components: always
      show-details: always
      status:
        http-mapping:
          up: 207
          unknown: 207
          down: 503
          out_of_service: 503
    shutdown:
      enabled: true