services:
  server-app:
    build:
      context: ../server-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: always
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"